name: Filter Sleeper NFL Players

on:
  schedule:
    - cron: "0 9 * * *" # runs every day at 9 AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run filter script
        run: python filter_players.py

      - name: Commit filtered file and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add docs/players_2025.json
          git commit -m "Update filtered players file" || echo "No changes to commit"
          git push

